---
version: '3.8'

services:
  ch3-app:
      build:
        context: .
      image: ch3-image
      container_name: ch3-app
      ports: 
      - "30000:3000"
      volumes:
      - ./src:/usr/src/app
      environment:
        RAILS_ENV: development
        DATE_FIX: '2021-03-15'
      stdin_open: true # docker run -i
      tty: true        # docker run -t
